### ISSUE TITLE
Add YOLO object detection implementation

### ISSUE THREAD

**Issue by laggui** [tracel-ai/models#21]
As a step forward in computer vision applications, we should offer an object detection model implementation.

The YOLO series seems like a good candidate.

Would have to check which variant is best based on the latest articles but also the licenses (I know the ultralytics stuff  is licensed under some GPL type licenses, which is not always ideal for some end applications).

**Comment by Luni-4** [comment]
This `burn` issue is realted https://github.com/tracel-ai/burn/issues/675

**Comment by laggui** [comment]
@Luni-4 I need your opinion on this.

Most of the recent YOLO detectors are based on the ultralytics stuff which is under some form of GPL license (strong copyleft license, i.e. using this code in your software means that you also have to distribute your software under that license and thus share the code publicly). I would think that transposing the implementation and importing their pre-trained weights would apply to the license.

On the other hand, YOLOX](https://github.com/Megvii-BaseDetection/YOLOX) is apache 2.0 but has slightly lower mAP on COCO.

For fine-tuning on a custom dataset, I would think the difference is probably negligible.

Do you have a preference for YOLOv8 (strong copyleft license, might restrict usage that is not public) vs another YOLO variant with a permissible license?

**Comment by Luni-4** [comment]
@laggui 

Thanks a lot for your analysis! So is `ONNX` subjected to the same `GPL` license if we are going to import it through `burn-import`?  May we ask to ultralytics if they are willing to re-license YOLOV8 so that we can implement it in `burn`?

For what concerns your last question, yep, any YOLO variant with a more permissible license is fine for me.

**Comment by laggui** [comment]
Thanks for your input!

Code artifacts like a model (or in this case ONNX model) are always a bit of a gray area in terms of copyright and licensing I think.. so I can't give you a definite answer on that 😅 but maybe importing the onnx model will work.

I doubt they will re-license, they've been dragging the GPL license since their first implementation and they have a commercial product based on that where they offer an "enterprise license" it seems.

**Comment by laggui** [comment]
For YOLOX the [PAFPN](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/yolox/models/yolo_pafpn.py#L32) requires `interpolate(mode="nearest")`, will have to wait for [this outstanding issue](https://github.com/tracel-ai/burn/issues/455) to finalize the implementation.

**Comment by laggui** [comment]
[YOLOv9](https://github.com/WongKinYiu/yolov9) just released without an official license yet but it looks like it was a fork of the ultralytics stuff..

Another one bites the dust with GPL/AGPL license 🥲

**Comment by laggui** [comment]
Completed in #24
