### ISSUE TITLE
RoBERTa weights do not have encoders with norm_first: true

### ISSUE THREAD

**Issue by seurimas** [tracel-ai/models#30]
Through tracing `transformers` running the same model on a fill-mask task, I was able to determine that the execution of `transformers` and `bert-burn` diverge at the point where normalization happens.

Furthermore, using the lm_head weights for roberta-base and attaching a LM head model, I was able to verify that bert-burn's results are correct with `norm_first: false`, but entirely wrong for `norm_first: true`.

I'd be happy to provide a pull request, but I'm not sure whether other BERT models _do_ use `norm_first: true`. I'm very new to machine learning and am not familiar with this family of models.

**Comment by nathanielsimard** [comment]
Yeah I don't think Roberta actually use `norm_frist: true`, maybe that was a mistake, happy to review your PR :)
